service: iat-back

frameworkVersion: ">1.10.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1024
  timeout: 20
  stage: dev
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"

functions:
  listImages:
    handler: endpoints.listImages
    events:
      -http:
        path: listImages
        method: get