service: name-image-search

frameworkVersion: ">=1.10.0"

plugins:
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  stage: dev
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"

functions:
  facialAnalysis:
    handler: lambdaHandler.facialAnalysis
    events:
      - http:
          path: facialAnalysis
          method: get