service: dxlab-young-ct-2018-rekognition

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 10
  stage: dev
  region: ap-southeast-2
  stackTags:
    CostCentre: 'dxlab'
    Name: 'dxlab-young-ct-2018'
    Stack: 'dxlab'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'rekognition:*'
      Resource: '*'

functions:
  images:
    handler: handler.images
    events:
      - http:
          integration: lambda
          path: images
          cors: true
          method: get
  getFaces:
    handler: handler.getFaces
    events:
      - http:
          integration: lambda
          path: getFaces
          method: get
          cors: true
