service: imageService

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 10
  stage: dev
  region: ap-southeast-2

  iamRoleStatements:
   - Effect: Allow
     Action:
       - s3:*
     Resource: "*"
    # - Effect: "Allow"
    #   Action:
    #     - "rekognition:*"
    #   Resource: "*"

functions:
  images:
    handler: handler.images
    events:
      - http:
          integration: lambda
          path: images
          cors: true
          method: get
  image:
    handler: handler.image
    events:
      - http:
          integration: lambda
          path: images/{filename}
          method: get
          cors: true
          request:
            paramaters:
              paths:
                filename: true