'use strict';

// tests for facialAnalysis
// Generated by serverless-jest-plugin

const mod = require('./../endpoints');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'facialAnalysis' });

describe('facialAnalysis', () => {
  beforeAll((done) => {

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).toBeDefined();
    });
  });
});
